#cloud-config

write_files:
  - path: '/etc/systemd/journald.conf.d/50-limit-journal-size.conf'
    content: |
      [Journal]
      Compress=yes
      SystemMaxUse=500M
      SystemMaxFileSize=10M
  - path: '/etc/systemd/resolved.conf.d/10-fix_dns.conf'
    content: |
      [Resolve]
      DNS=8.8.8.8
      FallbackDNS=8.8.4.4
  - path: '/home/core/hub.conf'
    content: |
      upstream up_panamax_api {
        server PMX_API:3000;
      }
      upstream up_panamax_ui {
        server PMX_UI:3000;
      }

      server {
        rewrite_log on;
        listen       6001 ssl;
        server_name  localhost;
        error_page 497  https://$host:$server_port$request_uri;
        ssl on;
        ssl_certificate      /etc/nginx/cert/server.crt;
        ssl_certificate_key  /etc/nginx/cert/server.key;
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers   on;
        location / {
          proxy_pass http://up_panamax_api;
          proxy_set_header Host $host; # nginx public ip
          proxy_set_header X-Forwarded-Host $http_host; # same as the request HTTP_HOST
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # browser ip
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          # add_header "Access-Control-Allow-Origin" "*";
          # add_header "Access-Control-Allow-Methods" "*";
        }
      }
      server {
        rewrite_log on;
        listen       6002 ssl;
        server_name  localhost;
        error_page 497  https://$host:$server_port$request_uri;
        ssl on;
        ssl_certificate      /etc/nginx/cert/server.crt;
        ssl_certificate_key  /etc/nginx/cert/server.key;
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers   on;
        location / {
          proxy_pass http://up_panamax_ui;
          proxy_set_header Host $host; # nginx public ip
          proxy_set_header X-Forwarded-Host $http_host; # same as the request HTTP_HOST
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # browser ip
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          # add_header "Access-Control-Allow-Origin" "*";
          # add_header "Access-Control-Allow-Methods" "*";
        }
      }

coreos:
  update:
    reboot-strategy: 'off'
  units:
    - name: 'systemd-journald.service'
      command: 'reload-or-restart'
    - name: 'docker.service'
      drop-ins:
        - name: '50-insecure-registry.conf'
          content: |
            [Service]
            Environment='DOCKER_OPTS=--log-level="debug" --registry-mirror="http://195.220.224.6:8080" --insecure-registry="0.0.0.0/0"'
    - name: 'systemd-journal-gatewayd.service'
      command: 'start'
    - name: 'fleet.service'
      command: 'start'
    - name: 'panamax-metrics.service'
      command: 'start'
      content: |
        [Unit]
        Description=Panamax Metrics
        After=docker.service
        Requires=docker.service
        [Service]
        ExecStartPre=-/usr/bin/docker kill PMX_CADVISOR
        ExecStartPre=-/usr/bin/docker rm -f PMX_CADVISOR
        ExecStart=/usr/bin/docker run --name=PMX_CADVISOR --rm=true --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=3002:8080 google/cadvisor:latest -log_dir / --global_housekeeping_interval=30s --housekeeping_interval=17s
        ExecStop=/usr/bin/docker stop PMX_CADVISOR
        Restart=always
        [Install]
        WantedBy=multi-user.target
    - name: 'panamax-api.service'
      command: 'start'
      content: |
        [Unit]
        Description=Panamax API
        After=docker.service
        Requires=docker.service
        [Service]
        ExecStartPre=-/usr/bin/docker kill PMX_API
        ExecStartPre=-/usr/bin/docker rm PMX_API
        ExecStart=/usr/bin/docker run --name=PMX_API --rm=true -v /var/panamax-data:/usr/src/app/db/mnt -v /var/run/docker.sock:/run/docker.sock:rw  -e JOURNAL_ENDPOINT=http://172.17.42.1:19531 -v /var/run/fleet.sock:/var/run/fleet.sock:rw -t -p 3001:3000 devmediafi/panamax-api:latest
        ExecStop=/usr/bin/docker stop PMX_API
        Restart=always
        [Install]
        WantedBy=multi-user.target
    - name: 'panamax-ui.service'
      command: 'start'
      content: |
        [Unit]
        Description=Panamax UI
        After=panamax-api.service panamax-metrics.service
        [Service]
        ExecStartPre=-/usr/bin/docker kill PMX_UI
        ExecStartPre=-/usr/bin/docker rm -f PMX_UI
        ExecStart=/usr/bin/docker run --name=PMX_UI --rm=true -v /var/run/docker.sock:/run/docker.sock:rw --link=PMX_API:PMX_API --link=PMX_CADVISOR:PMX_CADVISOR -e 3000 -p 3000:3000  devmediafi/panamax-ui:latest
        ExecStop=/usr/bin/docker stop PMX_UI
        Restart=always
        [Install]
        WantedBy=multi-user.target
    - name: 'panamax-api-nginx.service'
      command: 'start'
      content: |
        [Unit]
        Description=Panamax Nginx frontend
        After=panamax-api.service
        [Service]
        ExecStartPre=-/usr/bin/docker kill PMX_API_NGINX
        ExecStartPre=-/usr/bin/docker rm -f PMX_API_NGINX
        ExecStart=/usr/bin/docker run --name=PMX_API_NGINX --rm=true -t -v /dev/urandom:/dev/random -v /home/core/hub.conf:/etc/nginx/sites-enabled/hub.conf --link=PMX_API:PMX_API --link=PMX_UI:PMX_UI -e 6001 -p 6001:6001 -e 6002 -p 6002:6002 cgeoffroy/nginx-auto_cert:latest
        ExecStop=/usr/bin/docker stop PMX_API_NGINX
        Restart=always
        [Install]
        WantedBy=multi-user.target